# Generated by Django 5.0.4 on 2024-04-10 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_exercise_alter_message_content_exercisebyperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='exercisebyperson',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='OneDayOfWork',
        ),
    ]
