# Generated by Django 5.0.4 on 2024-04-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_routine_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisebyperson',
            name='series',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
