# Generated by Django 5.0.4 on 2024-04-11 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_routine_exercises_exercisebyperson_routine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisebyperson',
            name='routine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.routine'),
        ),
    ]
