# Generated by Django 5.0.4 on 2024-04-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_exercisebyperson_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='title',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
